<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>guru.mocker</groupId>
        <artifactId>parent</artifactId>
        <version>1.0.20</version>
    </parent>

    <groupId>guru.mocker.composition</groupId>
    <artifactId>java-composition-reactor</artifactId>
    <version>0.1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>Java Composition</name>
    <description>Java source code preprocessor for Concise Method Bodies (JEP 8209434),
        a preview implementation available for Java 8, 11, 17, 21, and 25.
    </description>
    <url>https://github.com/verhasi/java-composition</url>

    <modules>
        <module>parent</module>
        <module>preprocessor</module>
        <module>java-composition-maven-plugin</module>
        <module>integration-tests</module>
    </modules>

    <scm>
        <!--suppress UnresolvedMavenProperty -->
        <url>${guru.mocker.composition.scm.url}</url>
        <connection>scm:git:${project.scm.url}</connection>
        <developerConnection>${project.scm.connection}</developerConnection>
        <tag>HEAD</tag>
    </scm>

    <profiles>
        <profile>
            <id>release</id>
            <properties>
                <!--suppress UnresolvedMavenProperty -->
                <guru.mocker.composition.scm.url>${BITBUCKET_GIT_HTTP_ORIGIN}</guru.mocker.composition.scm.url>
            </properties>
        </profile>
    </profiles>
</project>
